### ISSUE TITLE
Strona 9 - Amen - tenor

### ISSUE THREAD

**Issue by Phitherek** [Antypion/spiewniktriduum2018#2]
Nie wiem, czy mamy śpiewać w końcu dwa czy trzy Amen w tenorach, trzeba to z siostrą ostatecznie ustalić.

**Comment by Antypion** [comment]
Poszło pytanie do Siostry, jak ma być

**Comment by Antypion** [comment]
@Phitherek A jak śpiewacie, bo siostra nie pamięta?

**Comment by Phitherek** [comment]
@Antypion to spytaj Tomka, bo ja też nie pamiętam na której wersji ostatnio stanęło.

**Comment by Antypion** [comment]
@Phitherek Siostra stwierdziłą, że 3 Amen może być, zamykam
